version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/chatapp/*'
    - 'ROOT/WEB-INF/classes/com/chatapp/configuration/*'
    - 'ROOT/WEB-INF/classes/com/chatapp/controller/*'
    - 'ROOT/WEB-INF/classes/com/chatapp/dao/*'
    - 'ROOT/WEB-INF/classes/com/chatapp/model/*'
    - 'ROOT/WEB-INF/classes/com/chatapp/service/*'
    - 'ROOT/WEB-INF/lib/*'
    - 'ROOT/WEB-INF/views/*'
    - 'ROOT/WEB-INF/views/chatBox/*'
    - 'ROOT/WEB-INF/views/LoginAndRegister/*'
    - 'ROOT/WEB-INF/views/user/*'
    - 'ROOT/resources/*'
    - 'ROOT/resources/bootstrap-3.3.7-dist/*'
    - 'ROOT/resources/bootstrap-3.3.7-dist/css/*'
    - 'ROOT/resources/bootstrap-3.3.7-dist/fonts/*'
    - 'ROOT/resources/bootstrap-3.3.7-dist/js/*'
    - 'ROOT/resources/chatBox/*'
    - 'ROOT/resources/font-awesome-4.7.0/*'
    - 'ROOT/resources/font-awesome-4.7.0/css/*'
    - 'ROOT/resources/font-awesome-4.7.0/fonts/*'
    - 'ROOT/resources/font-awesome-4.7.0/less/*'
    - 'ROOT/resources/LoginAndRegister/*'
    - 'ROOT/resources/user/*'
